public with sharing class Constants {
    public static final String INVALID_QUERY_OBJECT = 'Invalid Object To Query';
    public static final String SOQL_SELECT = 'SELECT ';
    public static final String SOQL_FROM = ' FROM ';
    public static final String SOQL_WHERE = ' WHERE ';
    public static final String SOQL_LIMIT = ' LIMIT ';
    public static final String SOQL_ORDERBY = ' ORDER BY ';
    public static final String SOQL_GROUPBY = ' GROUP BY ';
    public final static String RC = 'RC';
    public static final String INTEGRATION_USER_EMAIL = 'rrintegrationuser@rightrev.com';
    public static final Integer GENERAL_BATCH_SIZE = 2000;
    public static final String STRING_SPACE = ' ';
    public static final String STRING_AND_SPACE = ' AND ';
    public static final String STRING_UNDERSCORE = '_';
    public static final String COMMA = ',';
    public final static String FIELD_ID = 'Id';
    public final static String FIELD_NAME = 'Name';
}